version: '3'
services:
  openeo-test-api:
    build:
      context: .
      dockerfile: DOCKERFILE
    image: openeo-test-api:latest
    environment:
      USERNAME: "testuser"
      PASSWORD: "testpassword"
    container_name: openeo-test-api
    ports:
      - "80:8080"
      - "443:443"
